import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "components/header";
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LinkedIn App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <header className="border-b sticky top-0 bg-white z-50">
          <Toaster position="bottom-left" />
          
            <Header />
          </header>

          <div className="bg-[#f4f2ed] flex-1 w-full">
            <main className="max-w-6xl mx-auto"> 
            {children} 
            </main> 
          </div>
     
        </body>
    </html>
   </ClerkProvider>
  );
}
